import type { Metadata } from "next";
import { Outfit, Great_Vibes, Google_Sans } from "next/font/google";
import "./globals.css";
import PageTransition from "./components/PageTransition";

const outfit = Outfit({
  variable: "--font-outfit",
  subsets: ["latin"],
});

const greatVibes = Great_Vibes({
  variable: "--font-great",
  weight: ['400'],
  subsets: ['latin']
});

const googleSans = Google_Sans({
  variable: "--font-google",
  subsets: ['oriya']
})

export const metadata: Metadata = {
  title: "Supple",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: LayoutProps<"/">) {
  return (
    <html
      lang="en"
      className={`${outfit.variable} ${greatVibes.variable} ${googleSans.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
        <PageTransition>{children}</PageTransition>
      </body>
    </html>
  );
}
