# Generated by Django 6.1.1 on 2026-09-22 14:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foods', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='food',
            name='createdAt',
        ),
    ]
